@startuml
'https://plantuml.com/sequence-diagram

box Remote #Lightblue
entity "Remote VCell" #seagreen
database "Storage"
end box

box Local
participant Fiji
participant "VCell App"
actor User
end box

title Highest Level View of accessing remote files

User -> "VCell App": Make model
"VCell App" -> "Remote VCell": Makes simulation

"Remote VCell" --> "Storage": Store results of simulation

User -> Fiji: Access remote simulation
Fiji -> "Storage": Request model
"Storage" --> Fiji: Return model
note over "Storage": When returning model\nuse algorithms so that\nusers machine is not\nslow from brute loading\nimage.

Fiji --> User: Display image
User -> Fiji: Do any processing required












@enduml