@startuml
'https://plantuml.com/sequence-diagram

!pragma teoz true

box Remote #Lightblue
entity "Remote VCell" #seagreen
database "Storage"
queue "VCell API"

end box

box Local
box Fiji Plugins #Orange
participant VCellJ
end box
participant "VCell App"
actor User
end box

title Cloud File Storage

== Simulate Model ==

User -> "VCell App": Make model
"VCell App" -> "VCell API": Initiate simulation
"VCell API" -> "Remote VCell": Begin simulation

"Remote VCell" --> "Storage": Store results of simulation
"Remote VCell" --> "VCell App": All Finished notice

== Access Model==

User -> VCellJ: Access model with unique ID XXXX

"S3 API" -> "Storage Proxy": Approve request
note over "S3 API": Depending on the type\n of request different  \nresponses will be had\n ex. HEAD,GET,PUT
"Storage Proxy" -> "Storage": Tell storage system\n ID XXXX desires to be pulled
"Storage" --> "VCell API": Return model
"VCell API" --> VCellJ: Return model
note over "Storage": When returning the model\nit does not have to return the \nthe whole model but can do \nchunks depending on the file\n type
note over "S3 API": This API does not limit\n itself to only ImageJ.

VCellJ --> User: Display image
User -> VCellJ: Do any processing required


@enduml